UPDATE public.eservice SET employee = null, newuser = null, name = 'Поликлиника', number = 911, service = null, usluga = null, registration_time = null, email = null WHERE id = 51;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Охрана', number = 2, service = null, usluga = null, registration_time = null, email = null WHERE id = 52;
UPDATE public.eservice SET employee = null, newuser = null, name = 'служба такси', number = 111, service = null, usluga = null, registration_time = null, email = null WHERE id = 53;
UPDATE public.eservice SET employee = null, newuser = null, name = 'служба такси', number = 2, service = null, usluga = null, registration_time = null, email = null WHERE id = 55;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Звонок домой', number = 22585, service = null, usluga = null, registration_time = null, email = null WHERE id = 57;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Звонок другу', number = 89212121, service = null, usluga = null, registration_time = null, email = null WHERE id = 58;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Полиция', number = 927400365, service = null, usluga = null, registration_time = null, email = null WHERE id = 59;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Такси', number = 911, service = null, usluga = null, registration_time = null, email = null WHERE id = 61;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Уборка снега', number = 277777, service = null, usluga = null, registration_time = null, email = null WHERE id = 62;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Выезд инженера', number = 77777, service = null, usluga = null, registration_time = null, email = null WHERE id = 63;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Обработка запроса', number = 2777777, service = null, usluga = null, registration_time = null, email = null WHERE id = 64;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Доставка еды', number = 111111, service = null, usluga = null, registration_time = null, email = null WHERE id = 65;
UPDATE public.eservice SET employee = null, newuser = null, name = 'вызов врача', number = 777777, service = null, usluga = null, registration_time = null, email = null WHERE id = 66;
UPDATE public.eservice SET employee = null, newuser = null, name = 'Вызов сантехника', number = 275463, service = null, usluga = null, registration_time = null, email = null WHERE id = 67;